# list out the driver program source 
PROG_SRC = read-test.c tty-test.c
SRC = 

# SRC = 
CFLAGS = -DUNIX_TEST

DEPS = ./Makefile
SUPPORT_OBJS := $(SRC:.c=.o)
include $(CS140E_2022_PATH)/libunix/mk/Makefile.unix
