TEST_SRC := test-atag.c

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = my-install

# uncomment if you want it to automatically run.
RUN=1

include $(CS140E_2022_PATH)/libpi/mk/Makefile.template
