TEST_SRC = 0-circular-example.c 1-circular-example32.c

# if you need to override the install
BOOTLOADER = my-install

# automatically run the code
RUN = 1

include $(CS140E_2022_PATH)/libpi/mk/Makefile.template
