# makefile configuration
# define this if you need to give the device for your pi
TTYUSB = 

# the string to extract for checking
GREP_STR := 'TRACE:\|ERROR:\|PANIC:\|PASS:\|TEST:'

# set if you want the code to automatically run after building.
RUN = 1
# set if you want the code to automatically check after building.
#CHECK = 0

TEST_SRC := hello.c

include $(CS49N_2021_PATH)/libpi/mk/Makefile.template
