TEST_SRC = 1-gpio-int-ex.c 

# implement this code then copy it to libpi/src
SUPPORT_OBJS = gpio-int.o

# comment out interrupts-asm when you put in your own.

# if you need to override the install can change this (include the
# device name if you need it)
BOOTLOADER = my-install

# automatically run the code
RUN = 1

include $(CS140E_2022_PATH)/libpi/mk/Makefile.template
