TEST_SRC = 1-gpio-int-ex.c 2-logic-analyzer.c

STAFF_OBJS = interrupts-asm.o sw-uart.o

# if you need to override the install
BOOTLOADER = my-install

# automatically run the code
RUN = 1

include $(CS140E_2022_PATH)/libpi/mk/Makefile.template
